page_gen:
  - index_files: true
    data: glsp.projections
    template: glsp
    name: id
    dir: projections
  - index_files: true
    data: boxscores.data
    template: boxscores
    name: id
    dir: boxscores
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .env
  - .gitignore
  - yarn.lock
  - package.json
  - README.md